---
max_process: 3
devices:
  - 78:A5:04:17:68:6D
  - D0:5F:B8:5D:D0:3F
  - 78:A5:04:17:6E:00
  - D0:5F:B8:60:FD:7C
raw: false
log_dir: './logs/'
data_dir: './data/'
data_prefix: 'WED_data'
battery_warn: 20
min_logs: 10000
